### DISCUSSION TITLE
Compile error after upgrading to the latest stable

### DISCUSSION THREAD

**Discussion by isaacadariku** [Flutter-Bounty-Hunters/super_editor#1473] [Q&A]
@matthew-carroll we upgraded to the latest stable and keep getting this error.
```
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor
      ref: 6e40da6296e7deadd43ad205ba407905b67b8a4b // The new change, which the latest stable commit hash
      path: super_editor
```
![Screenshot 2023-09-27 at 22 10 50](https://github.com/superlistapp/super_editor/assets/46024202/9e9f996a-74aa-4526-bca5-3223e1b89f05)

We are using the latest Flutter version
<img width="613" alt="Screenshot 2023-09-28 at 18 07 26" src="https://github.com/superlistapp/super_editor/assets/46024202/ee4621b2-9ae7-4f49-9737-939dd6e07820">

If we revert back to the commit hash before the flutter 3.10 update [ed2cd44845079cff7c1962a6e081e5bdd8f2a188](https://github.com/superlistapp/super_editor/commit/ed2cd44845079cff7c1962a6e081e5bdd8f2a188), everything runs smoothly, also if we run the current stable example, it runs fine.

Please any help will be appreciated. Thanks!
